### ISSUE TITLE
Allow colored titlebar, headerbar (user edited gtk.css)

### ISSUE THREAD

**Issue by Trikenstein** [daniruiz/flat-remix-gtk#124]
Hi,

I am not sure why modern theme are only light gray or dark gray. Personally I distinguish better the overlapping windows when they have a colored titlebar. I can edit `gtk-3.0/gtk.css`  and add this code at the bottom.

```css
.titlebar, headerbar {
  background-color: #0063b3;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #003a6a;
}
```

This works almost OK. Only Gnome Tweaks seems not to have a colored headerbar on the left pane. But thats still OK as this is not an app I open often. However GTK2 apps definitely are insensitive to the change. I do the trick on some other themes and this works O, for example: [Juno](https://www.gnome-look.org/p/1280977/) or [Nordic](https://www.gnome-look.org/p/1267246/)

Hope the fix is not too complicate. Thanks.

**Comment by Trikenstein** [comment]
Screenshot showing the effects of adding at the bottom of `~/.themes/Flat-Remix-GTK-Teal-Dark-Solid/gtk-3.0/gtk.css`

```css
.titlebar, headerbar {
  background-color: #126670;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #0b3f46;
}
```

![FlatRemix_Dark_DifferentColors_Titlebar](https://user-images.githubusercontent.com/72353094/140621307-92b28cbb-d30d-4fd1-875d-2dfaba97dc14.png)
