### ISSUE TITLE
Unnecessary thick dark border around window

### ISSUE THREAD

**Issue by Trikenstein** [daniruiz/flat-remix-gtk#126]
Using dark solid theme, released on 2021-10-30. I think the tick dark border surrounding the window is un-necessary. Especially on unfocused windows.

**Comment by daniruiz** [comment]
What border do you refer to? Can you send a screenshot with an example?

**Comment by Trikenstein** [comment]
Hi sorry, 
Was a bit busy lately. Here is a screenshot showing the tick borders. This becomes particularly visible when I add a colored titlebar by adding this at the bottom of `~/.themes/Flat-Remix-GTK-Teal-Dark-Solid\gtk.css`

```css
.titlebar, headerbar {
  background-color: #126670;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #0b3f46;
}
```

Granted the colored titlebar is not part of the initial design. But still, do you think the thick border design is still relevant?

![FlatRemix_Dark_ThickBorders](https://user-images.githubusercontent.com/72353094/140621206-37387918-aef4-46f5-9c43-7e2285c972a5.png)
