### ISSUE TITLE
Issue with Libadwaita for non-gtk apps in titles bar

### ISSUE THREAD

**Issue by xylphute** [daniruiz/flat-remix-gtk#155]
Hi,

and thank you for your works. The update of flat-remix for gnome-shell is perfect. Now I have a trouble since I update to Fedora38 with gnome44 and flat-remix-libadwaita.
To get libadwaita apps look great I did:
`$ ln -s /usr/share/themes/Flat-Remix-LibAdwaita-Cyan-Dark/* .config/gtk-4.0/`
All gtk apps are good looking.
For qt apps I use QGtkStyle in qt5-qtstyleplugins and I had in /etc/profile
```
export QT_QPA_PLATFORMTHEME=gtk2
export QT_QPA_PLATFORM=xcb
```
It was perfect until F37 Gnome43, but today, the titles bar is strange
![Capture d’écran du 2023-04-21 10-54-11](https://user-images.githubusercontent.com/93719301/233592325-857290c0-7248-49c8-9cb2-fb0c96054c44.png)
![Capture d’écran du 2023-04-21 10-55-31](https://user-images.githubusercontent.com/93719301/233592607-6187efde-149d-4c60-9b13-f96bfb9e66eb.png)

If I unset files in .config/gtk-4.0/ , nautilus will be with default Adwaita theme and qt apps will have the correct flat-remix title bar

**Comment by xylphute** [comment]
I believed this issue only exists for non-gtk apps, but with gimp or adour, same problem

**Comment by magicbuffer** [comment]
Seeing the same issue, since i upgraded to gnome-shell 44

**Comment by Edalbegam** [comment]
Same issue on Arch Gnome 44.2. Not a big problem but still looking for a solution. Big fan of this theme BTW :D

**Comment by Soupy710** [comment]
Same issue here as well on arch gnome 44

**Comment by lem0nify** [comment]
Same issue

**Comment by lem0nify** [comment]
I discovered an interesting thing.
Instead of copying the `gtk.css` and `assets` files into `$HOME/.config/gtk-4.0`, I left them in `$HOME/.themes` but made some changes:
- in `$HOME/.themes/Flat-Remix-LibAdwaita-Blue-Dark` directory I created subfolder `gtk-4.0` and moved `assets` and `gtk.css` there
- I opened the `gtk.css` file and at the beginning I added the line:
```css
@import url("resource:///org/gnome/Adwaita/styles/base.css");
```
- in the directory `$HOME/.themes/Flat-Remix-LibAdwaita-Blue-Dark` I created a file `index.theme` with the following content:
```ini
[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Flat-Remix-LibAdwaita-Blue-Dark
Comment="Flat-Remix-LibAdwaita-Blue-Dark theme"
Encoding=UTF-8


[X-GNOME-Metatheme]
GtkTheme=Flat-Remix-LibAdwaita-Blue-Dark
MetacityTheme=Flat-Remix-Dark-Metacity
IconTheme=Flat-Remix-Blue-Dark
CursorTheme=Adwaita
ButtonLayout=:minimize,maximize,close
```

In this way, I ended up with a standard file structure GTK theme that applies well to applications using libadwaita. Now it is enough to launch any such application with an environment variable:
```bash
GTK_THEME='Flat-Remix-LibAdwaita-Blue-Dark' nautilus
```
and it will apply even if the files in `$HOME/.config/gtk-4.0` are not replaced:

![image](https://github.com/daniruiz/flat-remix-gtk/assets/17163615/060d3b01-8473-4076-9fcd-12c27408c13e)

An interesting point is that in the same way you can run any non-gtk application, and its frame and buttons will not be broken:
```bash
GTK_THEME='Flat-Remix-LibAdwaita-Blue-Dark' wireshark
```

![image](https://github.com/daniruiz/flat-remix-gtk/assets/17163615/5a7becac-0a19-4e6d-bf7a-b68a3c96db53)

But if I add this variable to the `$HOME/.xprofile` file which gets sourced by the display manager:
```bash
export GTK_THEME='Flat-Remix-LibAdwaita-Blue-Dark'
```
and then restarting the display manager, I again get the same problem as when replacing files in `$HOME/.config/gtk-4.0`.

Of course, it is possible to modify the launchers of certain applications which use libadwaita to set an environment variable, but this is not a very convenient way, because I launch applications not only by clicking on the launcher. Also, some non-gtk applications can themselves run applications using libadwaita (eg 'Open Containing Folder' in VSCode). In this case, nautilus will inherit the VSCode environment variables where `GTK_THEME` is not present.

In general, I'm at a dead end, but maybe my post will help someone find a working solution to this problem. In that case, please write here. 🙏

**Comment by Deiv70** [comment]
I'm on **Manjaro**, **Gnome 44** with same problem also (the squared buttons on the window title) with "legacy" / gtk3 applications, such as:
- Timeshift-gtk
- VLC
- GIMP
- LibreOffice
- Kitty
- VS Code
- GitKraken
- ...

![Screenshot_2023-08-17_20-37-32](https://github.com/daniruiz/flat-remix-gtk/assets/87421890/320ab0f6-12fd-47a2-98a5-f7b63ff92273)

I'm going to leave here some info that could end up being helpful:

I can say that it's happening when on _**gnome-tweaks**_ I have _**legacy applications theme**_ set to:
- Flat-Remix-GTK-Magenta-Dark ( _that's why I'm here_ )
- Adwaita
- Adwaita-Dark
- HighContrast
- HighContrastInverse

But it's suddenly fixed (even with the _**flat-remix**_ colors) when it's other selected, such as:
- Adw
- Adw-dark
- Adw-gtk3 
- Adw-gtk3-dark

Obviously, this makes other applications that were working (such as _**gnome-tweaks**_, _**google-chrome**_, _**gedit**_, ...) return to the gnome default theme.

**Comment by Pranay-Chopra** [comment]
I have found a solution to this!

your ~/.config/gtk-4.0/gtk.css should look like this:

```css
@define-color accent_bg_color #06a284;
@define-color accent_fg_color #ffffff;
@define-color accent_color @accent_bg_color;
@define-color destructive_bg_color @red_4;
@define-color destructive_fg_color white;
@define-color destructive_color #ff7b63;
@define-color success_bg_color @green_5;
@define-color success_fg_color white;
@define-color success_color @green_1;
@define-color warning_bg_color #cd9309;
@define-color warning_fg_color rgba(0, 0, 0, 0.8);
@define-color warning_color @yellow_2;
@define-color error_bg_color @red_4;
@define-color error_fg_color white;
@define-color error_color #ff7b63;
@define-color window_bg_color #030303;
@define-color window_fg_color white;
@define-color view_bg_color black;
@define-color view_fg_color #ffffff;
@define-color headerbar_bg_color black;
@define-color headerbar_fg_color white;
@define-color headerbar_border_color white;
@define-color headerbar_backdrop_color @window_bg_color;
@define-color headerbar_shade_color rgba(0, 0, 0, 0.36);
@define-color card_bg_color rgba(255, 255, 255, 0.05);
@define-color card_fg_color white;
@define-color card_shade_color rgba(0, 0, 0, 0.36);
@define-color popover_bg_color #171717;
@define-color popover_fg_color white;
@define-color shade_color rgba(0, 0, 0, 0.36);
@define-color scrollbar_outline_color rgba(0, 0, 0, 0.5);
windowcontrols {
  border-spacing: 6px; }
  windowcontrols:not(.empty).start:dir(ltr), windowcontrols:not(.empty).end:dir(rtl) {
    margin-right: 7px; }
  windowcontrols:not(.empty).start:dir(rtl), windowcontrols:not(.empty).end:dir(ltr) {
    margin-left: 7px; }
  windowcontrols button {
    border-radius: 9999px;
    padding: 6px;
    margin: 0 2px;
    min-width: 0;
    min-height: 0; }
    windowcontrols button:hover {
      border-color: transparent;
      background-image: none;
      box-shadow: none;
      background-color: black; }
    windowcontrols button:active, windowcontrols button:checked {
      border-color: transparent;
      background-image: none;
      box-shadow: none;
      background-color: black; }
headerbar windowcontrols button.minimize,
    headerbar windowcontrols button.maximize,
    headerbar windowcontrols button.close {
      color: transparent;
      -gtk-icon-shadow: none;
      background-image: -gtk-scaled(url("assets/titlebutton.png"), url("assets/titlebutton@2.png"));
      background-position: center;
      background-repeat: no-repeat;
      background-size: 8px;
      margin: 0;
      padding: 0;
      min-width: 0;
      min-height: 0;
      box-shadow: none;
      border: none;
      transition: all .2s; }
      .titlebar:not(headerbar) windowcontrols button.minimize:backdrop, .titlebar:not(headerbar) windowcontrols button.maximize:backdrop, .titlebar:not(headerbar) windowcontrols button.close:backdrop,
      headerbar windowcontrols button.minimize:backdrop,
      headerbar windowcontrols button.maximize:backdrop,
      headerbar windowcontrols button.close:backdrop {
        background-color: #404040;
        background-image: -gtk-scaled(url("assets/titlebutton.png"), url("assets/titlebutton@2.png")); }
    .titlebar:not(headerbar) windowcontrols button.minimize,
    headerbar windowcontrols button.minimize {
      background-color: #fd7d00; }
      .titlebar:not(headerbar) windowcontrols button.minimize:hover,
      headerbar windowcontrols button.minimize:hover {
        background-image: -gtk-scaled(url("assets/minimize.png"), url("assets/minimize@2.png")); }
    .titlebar:not(headerbar) windowcontrols button.maximize,
    headerbar windowcontrols button.maximize {
      background-color: #377cf1; }
      .titlebar:not(headerbar) windowcontrols button.maximize:hover,
      headerbar windowcontrols button.maximize:hover {
        background-image: -gtk-scaled(url("assets/maximize.png"), url("assets/maximize@2.png")); }
    .titlebar:not(headerbar) windowcontrols button.close,
    headerbar windowcontrols button.close {
      background-color: #d31919; }
      .titlebar:not(headerbar) windowcontrols button.close:hover,
      headerbar windowcontrols button.close:hover {
        background-image: -gtk-scaled(url("assets/close.png"), url("assets/close@2.png")); }
```

im using the darkest-solid variant of the green theme, so you may have to change the colors, but it works flawlessly
